In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame({'x':['a']*4+['b']*4,'y':[1,0,1,0,1,0,1,1]})

In [3]:
class ResponseEncoder:
    def __init__(self):
        self.features={}# stores posterior class probabilities for each value of column(p(y==class)/feature=fi)
        self.default=[]# contains mean for each class label.Useful if we encounter new category while tranforming data
    def fit(self,df,column,response):
        """
        df-> dataframe
        column->  column name that you want to perfrom response encoding
        response-> response column name to check for class labels
        """
        labels=list(df[response].unique())
        for each in df[column].unique():
            temp=df[df[column]==each]
            dict_=dict(temp[response].value_counts())
            feature=[]
            for label in labels:
                if label in dict_:
                    feature.append(dict_.get(label)/len(temp))
                else:
                    feature.append(0)
            self.features[each]=feature

        for label in labels:
            self.default.append(len(df[df[response]==label])/len(df))
    
    def transform(self,series):
        encoded=[]
        for each in series:
            encoded.append(self.features.get(each,self.default))
        

        return np.array(encoded)
    def fit_transform(self,df,column,response):
        self.features={}
        self.default=[]
        self.fit(df,column,response)
        return self.transform(df[column])
            
        
    

In [4]:
c=ResponseEncoder()
c.fit(df,column='x',response='y')

In [5]:
c.transform(df['x'])

array([[0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.75, 0.25]])

In [6]:
c.transform(pd.Series(['c','d','e']))#just returning mean value as these values are not present in train data

array([[0.625, 0.375],
       [0.625, 0.375],
       [0.625, 0.375]])

In [7]:
c.fit_transform(df,'x','y')#fitting and transforming both 

array([[0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.75, 0.25]])